from mongoengine import *

class HouseMaster(Document):
	houseMasterFirstName = StringField(max_length=100)
	houseMasterLastName = StringField(max_length=100)
	houseClass = StringField(max_length=20)
	emailId = StringField(max_length=100)
	phoneNumber = StringField(max_length=50)
	refLink = StringField()
	houseMasterId = StringField()
	password = StringField()
	compOfLeaves = IntField()
	paidLeaves = IntField()
	casualLeaves = IntField()
	status = IntField()
	createdOn = DateTimeField()


class ApplyLeave(Document):
	trainerName = StringField()
	leaveType = StringField()
	fromDate = StringField()
	toDate = StringField()
	hrEmail = StringField()
	accountEmail = StringField()
	managerEmail = StringField()
	reasonApply = StringField()
	houseMasterId = ReferenceField('HouseMaster')
	refLink = StringField()
	applyDate = DateTimeField()
	status = IntField()
	createdOn = DateTimeField()

class AmountBank(Document):
	studentName = StringField(max_length=100)
	className = StringField(max_length=100)
	houseMasterName = ReferenceField('HouseMaster')
	studentTotalAmount = IntField()
	link = StringField()
	refLink = StringField()
	status = IntField(default=1)
	createdOn = DateTimeField()
	

class StudentTransaction(Document):
	studentId = ReferenceField('AmountBank')
	studentName= StringField()
	creditAmount = IntField()
	debitAmount = IntField()
	reasonTaking = StringField(max_length=100)
	takenCreditDate = DateTimeField()
	takenDebitDate = DateTimeField()
	amountDebitStatus = IntField()
	amountCreditStatus = IntField()
	link=StringField()
	createdOn = DateTimeField()

class GateVisit(Document):
	firstname = StringField()
	lastname = StringField()
	reason = StringField()
	mobile = StringField()
	date = DateTimeField()
	time = DateTimeField()
	status = IntField()

class WellnessCenterRegistration(Document):
	firstName = StringField()
	lastName = StringField()
	emailId = StringField()
	phoneNumber = StringField()
	password = StringField()
	profilePic = StringField()
	hsRefLink = StringField()
	createdOn = DateTimeField()
	status = IntField()

class StudentDailySickRegistration(Document):
	studentName = StringField()
	className = StringField()
	rollNumber = StringField()
	diseaseName = StringField()
	date = StringField()
	time = StringField()
	day = StringField()
	medicineIssued = StringField()
	permissionLetter = StringField()
	hsRefLink = ReferenceField('WellnessCenterRegistration')
	hsId = ReferenceField('WellnessCenterRegistration')
	hsName = ReferenceField('WellnessCenterRegistration')
	studentRefLink = StringField()
	createdOn = DateTimeField()
	status = IntField()


class StudentSickDiet(Document):
	studentName = StringField()
	className = StringField()
	rollNumber = StringField()
	studentRefLink = StringField()
	studentId = ReferenceField('StudentDailySickRegistration')
	hsId = ReferenceField('WellnessCenterRegistration')
	# hsRefLink = ReferenceField('WellnessCenterRegistration')
	medicineIssued = StringField()
	diseaseName = StringField()
	foodItem = StringField()
	foodQuantity = StringField()
	numberOfTimes = StringField()
	sickDietStudentRefLink = StringField()
	createdOn = DateTimeField()
	sickDietStatus = IntField()
	dietAddedOn = DateTimeField()
	recoverdOn = DateTimeField()
	status = IntField()

class StudentDetails(Document):
	rollNumber  = StringField()
	className = StringField()
	firstName = StringField()
	lastName = StringField()
	studentRefLink = StringField()
	height = StringField()
	weight = StringField()
	hemoglobin = StringField()
	age = StringField()
	month = StringField()
	bmiValue = StringField()
	createdOn = DateTimeField()
	attendanceStatus = IntField(default=2)
	attendenceDate = DateTimeField()
	status = IntField()

class ClassTeacherRegister(Document):
	classTeacherFirstName = StringField(max_length=100)
	classTeacherLastName = StringField(max_length=100)
	className = StringField(max_length=20)
	emailId = StringField(max_length=100)
	phoneNumber = StringField(max_length=50)
	classTeacherRefLink = StringField()
	classTeacherId = StringField()
	password = StringField()
	status = IntField()
	createdOn = DateTimeField()

class StudentAttendanceRegister(Document):
	firstName = StringField()
	lastName = StringField()
	className = StringField()
	rollNumber= StringField()
	studentAttendanceLink = StringField()
	classTeacherRefLink = ReferenceField('ClassTeacherRegister')
	attendenceDate = DateTimeField()
	attendanceStatus = IntField(default=2)
	status = IntField()
	createdOn = DateTimeField()
	attendenceSaveDate = DateTimeField()
